---
training_file: "20220727_p.tsv"
batch_size: 16
embedding_dim: 0
epochs: 6
learning_rate: 0.00001
max_features: 0
min_delta: 0.05
patience: 2
sequence_length: 280
test_size: 0.1
model: >
    loss = tensorflow.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    optimizer = tensorflow.keras.optimizers.Adam(learning_rate=modelcfg["learning_rate"])
    metrics = tensorflow.keras.metrics.SparseCategoricalAccuracy("accuracy")
    model = transformers.TFBertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone', num_labels=3, from_pt=True)
    tokenizer = transformers.BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
rmk: >
    original labels = {0:'neutral', 1:'positive', 2:'negative'}
