#!/usr/bin/env python3

from src import *
import argparse
import json
import logging
import os
import sys

logging.basicConfig(level=logging.INFO)

fmap = {
	"predict": model.predict,
	"replay"  : db.replay,
	"store": db.store,
	"stream" : stream.stream,
	"train"  : model.train,
}

argp = argparse.ArgumentParser(
	prog="hypnox",
	usage="%(prog)s [options] command",
	description='''
		  _        _
	 |_| \_/ |_) |\ | / \ \/
	 | |  |  |   | \| \_/ /\\

	   sub noctem sapientia
	''',
	formatter_class=argparse.RawTextHelpFormatter)
argp.add_argument("-i", "--input", help="csv data file to use as input")
argp.add_argument("-m", "--model", help="name of model to use or save")
argp.add_argument("command", choices=fmap.keys())
args = argp.parse_args()

try:
	args.config = json.load(open(os.path.dirname(os.path.realpath(__file__)) + "/.env"))
except:
	logging.error(".env file not found! e.g. `ln -s .env.dev .env`")
	sys.exit(1)

func = fmap[args.command]
func(argp, args)

