#!/usr/bin/env python3

import argparse
import hypnox

fmap = {
	"train"  : hypnox.train,
	"replay"  : hypnox.replay,
	"stream" : hypnox.stream,
}

argp = argparse.ArgumentParser(description='''
          _        _
 |_| \_/ |_) |\ | / \ \/
 | |  |  |   | \| \_/ /\\

   sub noctem sapientia
''',
formatter_class=argparse.RawTextHelpFormatter)
argp.add_argument("--input", help="csv data file to use as input")
argp.add_argument("--model", help="name of model to use or save")
argp.add_argument("command", choices=fmap.keys())
args = argp.parse_args()

func = fmap[args.command]
func(argp, args)

