#!/usr/bin/env python3

import argparse
import hypnox
import os
import twitter_stream

fmap = {
	"stream" : twitter_stream.stream,
}

argp = argparse.ArgumentParser(description='''
          _        _
 |_| \_/ |_) |\ | / \ \/
 | |  |  |   | \| \_/ /\\

   sub noctem sapientia
''',
formatter_class=argparse.RawTextHelpFormatter)
argp.add_argument("--input", help="file containing tweets to process")
argp.add_argument("command", choices=fmap.keys())
args = argp.parse_args()

func = fmap[args.command]
func(argp, args)

