---
training_file: "20220729.tsv"
batch_size: 16
embedding_dim: 0
epochs: 9
learning_rate: 0.00000666
max_features: 0
min_delta: 0.03
patience: 1
sequence_length: 280
test_size: 0.15
model: >
    loss = tensorflow.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    optimizer = tensorflow.keras.optimizers.Adam(learning_rate=modelcfg["learning_rate"])
    metrics = tensorflow.keras.metrics.SparseCategoricalAccuracy("accuracy")
    model = transformers.TFBertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone', num_labels=3, from_pt=True)
    tokenizer = transformers.BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
rmk: >
    labels = {0:'neutral', 1:'positive', 2:'negative'}
