---
training_file: "20220729.tsv"
batch_size: 32
embedding_dim: 32
epochs: 9
learning_rate: 0.000033
max_features: 22000
min_delta: 0.03
patience: 2
sequence_length: 280
test_size: 0.15
model: >
model: >
    loss = tensorflow.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer = tensorflow.keras.optimizers.Adam(learning_rate=modelcfg["learning_rate"]),
    metrics = tensorflow.metrics.BinaryAccuracy("accuracy")
    model = tensorflow.keras.Sequential([
        tensorflow.keras.layers.Embedding(max_features + 1, embedding_dim, mask_zero=True),
        tensorflow.keras.layers.Bidirectional(tensorflow.keras.layers.LSTM(128, return_sequences=True)),
        tensorflow.keras.layers.Bidirectional(tensorflow.keras.layers.LSTM(32)),
        tensorflow.keras.layers.Dense(64, activation="relu"),
        tensorflow.keras.layers.Dropout(0.5),
        tensorflow.keras.layers.Dense(1)
    ])
