---
class: "polarity"
training_file: "20220729.tsv"
bert: "yiyanghkust/finbert-tone"
num_labels: 3
test_size: 0.112
max_length: 128
batch_size: 16
epochs: 9
learning_rate: 0.000112
min_delta: 0.0418
patience: 2
rmk: >
