---
class: "intensity"
bert: "yiyanghkust/finbert-pretrain"
num_labels: 2
test_size: 0.15
max_length: 156
batch_size: 32
epochs: 33
learning_rate: 0.0000015
min_delta: 0.005
patience: 3
monitor: "val_loss"
